version: '2'

services:
  web:
    build:
      context: ./containers/
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    links:
      - app
  app:
    build:
      context: ./containers/
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    ports:
      - "9000"
    links:
      - blackfire
      - db
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
      - BLACKFIRE_LOG_LEVEL=4
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
  selenium:
    image: selenium/standalone-chrome:3.4.0-einsteinium
    ports:
      - "4444:4444"
